### ISSUE TITLE
Validate Currency Doesn't include currencies from all countries

### ISSUE THREAD

**Issue by erwagasore** [xeBuz/Flask-Validator#21]
The currency dictionary should be base on ISO 4217 which is the completest list available

Here is a list of libraries trying to handle currency the ISO way

1. [https://github.com/spoqa/iso4217](url)
2. [https://github.com/limist/py-moneyed](url)

**Comment by xeBuz** [comment]
I implemented `py-moneyed`, thank you for the suggestion! :+1:

**Comment by erwagasore** [comment]
Nice! :+1:
