### ISSUE TITLE
Fix docs mistyped "length"

### ISSUE THREAD

**Issue by oliveiraev** [xeBuz/Flask-Validator#42]
Official docs have ```length``` typed as ```lenght``` everywhere.

I can fix it if you tell me where it is.

**Comment by xeBuz** [comment]
Can you show me exactly where? That was fixed several months ago.
http://flask-validator.readthedocs.io/en/latest/validators.html

**Comment by oliveiraev** [comment]
http://pythonhosted.org/Flask-Validator/

It's the link that I got from [pypi](https://pypi.python.org/pypi/Flask-Validator/)

**Comment by xeBuz** [comment]
Oh thanks, I forgot to update that one
I will update it later

**Comment by xeBuz** [comment]
I deleted the documentation hosted on that server, I don't want to maintain 2 documentations :)
